swagger: '2.0'
info:
  title: Smart Door Authentication System API
  description: 'Smart Door Authentication System API for assignment 2.'
  version: 1.0.0
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /registerGuest:
    post:
      summary: WP1 which was sent to owner.
      description: |
        Takes guest's name and his/her phone number
      tags:
        - Owner
      operationId: sendMessage_owner
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/newGuestRequest'
      responses:
        '200':
          description: A new guest registered response
          schema:
            $ref: '#/definitions/newGuestResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /sendOTP:
    post:
      summary: WP2 which was sent to guest.
      description: |
        Takes password
      tags:
        - Guest
      operationId: sendMessage_guest
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/validateOTPRequest'
      responses:
        '200':
          description: a valid OTP response
          schema:
            $ref: '#/definitions/validateOTPResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
definitions:
  newGuestRequest:
    type: object
    properties:
      messages:
        type: array
        items:
          $ref: '#/definitions/Message'
  newGuestResponse:
    type: object
    properties:
      messages:
        type: array
        items:
          $ref: '#/definitions/Message'
  validateOTPRequest:
    type: object
    properties:
      messages:
        type: array
        items:
          $ref: '#/definitions/Message'
  validateOTPResponse:
    type: object
    properties:
      messages:
        type: array
        items:
          $ref: '#/definitions/Message'
  Message:
    type: object
    properties:
      type:
        type: string
      unstructured:
        $ref: '#/definitions/UnstructuredMessage'
  UnstructuredMessage:
    type: object
    properties:
      id:
        type: string
      text:
        type: string
      timestamp:
        type: string
        format: datetime
  
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string